const $=id=>document.getElementById(id);
const els={file:$('fileInput'),src:$('sourceCanvas'),preview:$('previewCanvas'),detect:$('detectBtn'),clear:$('clearBtn'),sort:$('sortBtn'),del:$('deleteBtn'),list:$('frameList'),play:$('playBtn'),stop:$('stopBtn'),exportSheet:$('exportSheetBtn'),exportFrames:$('exportFramesBtn'),status:$('status')};
const sctx=els.src.getContext('2d',{willReadFrequently:true});
const pctx=els.preview.getContext('2d');
pctx.imageSmoothingEnabled=false;
let img=null,frames=[],selected=-1,animTimer=null,drag=null;

function setStatus(t){els.status.textContent=t}
function enable(v){['detect','clear'].forEach(k=>els[k].disabled=!v); updateActionButtons()}
function updateActionButtons(){const v=frames.length>0;['sort','play','stop','exportSheet','exportFrames'].forEach(k=>els[k].disabled=!v);els.del.disabled=selected<0; $('endFrame').value=Math.max(1,frames.length);$('startFrame').max=Math.max(1,frames.length);$('endFrame').max=Math.max(1,frames.length)}

els.file.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const im=new Image();im.onload=()=>{img=im;els.src.width=im.width;els.src.height=im.height;sctx.clearRect(0,0,im.width,im.height);sctx.drawImage(im,0,0);frames=[];selected=-1;enable(true);renderSource();renderFrames();drawPreview(0);setStatus(`${f.name}  ${im.width}×${im.height}px を読み込みました。`)};im.src=URL.createObjectURL(f)});

$('alphaThreshold').addEventListener('input',e=>$('alphaValue').textContent=e.target.value);
els.detect.addEventListener('click',detectFrames);
els.clear.addEventListener('click',()=>{frames=[];selected=-1;renderSource();renderFrames();updateActionButtons();setStatus('認識領域をすべて解除しました。')});
els.sort.addEventListener('click',()=>{frames.sort((a,b)=>Math.abs(a.y-b.y)>Math.max(a.h,b.h)*.45?a.y-b.y:a.x-b.x);renderFrames();renderSource();setStatus('フレームを上→下、左→右で並べ替えました。')});
els.del.addEventListener('click',()=>{if(selected<0)return;frames.splice(selected,1);selected=-1;renderFrames();renderSource();updateActionButtons()});

function detectFrames(){if(!img)return;const w=els.src.width,h=els.src.height,data=sctx.getImageData(0,0,w,h).data;const aT=+$('alphaThreshold').value,minArea=+$('minArea').value,merge=+$('mergeDistance').value,pad=+$('boxPadding').value;const seen=new Uint8Array(w*h);const comps=[];const qx=new Int32Array(w*h),qy=new Int32Array(w*h);
 const opaque=(x,y)=>data[(y*w+x)*4+3]>=aT;
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){const idx=y*w+x;if(seen[idx]||!opaque(x,y))continue;let head=0,tail=0,area=0,minx=x,maxx=x,miny=y,maxy=y;seen[idx]=1;qx[tail]=x;qy[tail++]=y;while(head<tail){const cx=qx[head],cy=qy[head++];area++;if(cx<minx)minx=cx;if(cx>maxx)maxx=cx;if(cy<miny)miny=cy;if(cy>maxy)maxy=cy;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=cx+dx,ny=cy+dy;if(nx<0||ny<0||nx>=w||ny>=h)continue;const ni=ny*w+nx;if(!seen[ni]&&opaque(nx,ny)){seen[ni]=1;qx[tail]=nx;qy[tail++]=ny}}}if(area>=minArea)comps.push({x:minx,y:miny,w:maxx-minx+1,h:maxy-miny+1,area});}
 frames=mergeComponents(comps,merge).map(r=>({x:Math.max(0,r.x-pad),y:Math.max(0,r.y-pad),w:Math.min(w,r.x+r.w+pad)-Math.max(0,r.x-pad),h:Math.min(h,r.y+r.h+pad)-Math.max(0,r.y-pad)}));
 frames.sort((a,b)=>Math.abs(a.y-b.y)>Math.max(a.h,b.h)*.45?a.y-b.y:a.x-b.x);selected=-1;renderSource();renderFrames();updateActionButtons();setStatus(`${comps.length} 個の透明領域成分から ${frames.length} フレーム候補を認識しました。\n武器などが別扱いの場合は「部品結合距離」を大きくして再認識してください。`)}

function gap(a,b){const dx=Math.max(0,Math.max(a.x,b.x)-Math.min(a.x+a.w,b.x+b.w));const dy=Math.max(0,Math.max(a.y,b.y)-Math.min(a.y+a.h,b.y+b.h));return Math.hypot(dx,dy)}
function union(a,b){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),r=Math.max(a.x+a.w,b.x+b.w),bt=Math.max(a.y+a.h,b.y+b.h);return{x,y,w:r-x,h:bt-y}}
function mergeComponents(cs,d){let arr=cs.map(x=>({...x})),changed=true;while(changed){changed=false;outer:for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){if(gap(arr[i],arr[j])<=d){arr[i]=union(arr[i],arr[j]);arr.splice(j,1);changed=true;break outer}}}return arr}

function renderSource(){if(!img)return;sctx.clearRect(0,0,els.src.width,els.src.height);sctx.drawImage(img,0,0);sctx.save();sctx.lineWidth=2;frames.forEach((r,i)=>{sctx.strokeStyle=i===selected?'#ffd15c':'#4aa3ff';sctx.strokeRect(r.x+.5,r.y+.5,r.w,r.h);sctx.fillStyle=i===selected?'#ffd15c':'#4aa3ff';sctx.font='12px sans-serif';sctx.fillText(String(i+1),r.x+4,r.y+14);if(i===selected){for(const [x,y] of [[r.x,r.y],[r.x+r.w,r.y],[r.x,r.y+r.h],[r.x+r.w,r.y+r.h]])sctx.fillRect(x-4,y-4,8,8)}});sctx.restore()}
function canvasPos(e){const r=els.src.getBoundingClientRect();return{x:(e.clientX-r.left)*els.src.width/r.width,y:(e.clientY-r.top)*els.src.height/r.height}}
function hitFrame(x,y){for(let i=frames.length-1;i>=0;i--){const r=frames[i];if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)return i}return-1}
function hitHandle(r,x,y){const hs=9;const pts=[['tl',r.x,r.y],['tr',r.x+r.w,r.y],['bl',r.x,r.y+r.h],['br',r.x+r.w,r.y+r.h]];for(const p of pts)if(Math.abs(x-p[1])<hs&&Math.abs(y-p[2])<hs)return p[0];return null}
els.src.addEventListener('mousedown',e=>{if(!img)return;const p=canvasPos(e);if(e.shiftKey){drag={type:'new',sx:p.x,sy:p.y};return}const i=hitFrame(p.x,p.y);selected=i;if(i>=0){const h=hitHandle(frames[i],p.x,p.y);drag={type:h?'resize':'move',handle:h,i,sx:p.x,sy:p.y,orig:{...frames[i]}}}renderSource();renderFrames();updateActionButtons()});
window.addEventListener('mousemove',e=>{if(!drag)return;const p=canvasPos(e);if(drag.type==='move'){const r=frames[drag.i],o=drag.orig;r.x=Math.max(0,Math.min(els.src.width-r.w,o.x+p.x-drag.sx));r.y=Math.max(0,Math.min(els.src.height-r.h,o.y+p.y-drag.sy))}else if(drag.type==='resize'){const o=drag.orig;let x1=o.x,y1=o.y,x2=o.x+o.w,y2=o.y+o.h;if(drag.handle.includes('l'))x1=p.x;if(drag.handle.includes('r'))x2=p.x;if(drag.handle.includes('t'))y1=p.y;if(drag.handle.includes('b'))y2=p.y;frames[drag.i]={x:Math.max(0,Math.min(x1,x2)),y:Math.max(0,Math.min(y1,y2)),w:Math.max(1,Math.abs(x2-x1)),h:Math.max(1,Math.abs(y2-y1))}}renderSource()});
window.addEventListener('mouseup',e=>{if(!drag)return;if(drag.type==='new'){const p=canvasPos(e),x=Math.min(drag.sx,p.x),y=Math.min(drag.sy,p.y),w=Math.abs(p.x-drag.sx),h=Math.abs(p.y-drag.sy);if(w>2&&h>2){frames.push({x,y,w,h});selected=frames.length-1}}drag=null;renderSource();renderFrames();updateActionButtons()});

function frameCrop(f){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(f.w));c.height=Math.max(1,Math.round(f.h));const cctx=c.getContext('2d');cctx.imageSmoothingEnabled=false;cctx.drawImage(img,f.x,f.y,f.w,f.h,0,0,c.width,c.height);return c}
function footY(c){const d=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height).data,thr=+$('alphaThreshold').value;for(let y=c.height-1;y>=0;y--)for(let x=0;x<c.width;x++)if(d[(y*c.width+x)*4+3]>=thr)return y;return c.height-1}
function metrics(){const crops=frames.map(frameCrop);let maxW=0,maxAbove=0,maxBelow=0;for(const c of crops){const fy=$('autoFeet').checked?footY(c):c.height-1;maxW=Math.max(maxW,c.width);maxAbove=Math.max(maxAbove,fy+1);maxBelow=Math.max(maxBelow,c.height-fy-1)}const padX=+$('padX').value,padY=+$('padY').value;const autoW=maxW+padX*2,autoH=maxAbove+maxBelow+padY*2;return{crops,maxAbove,maxBelow,padX,padY,w:(+$('cellW').value)||autoW,h:(+$('cellH').value)||autoH}}
function normalizedFrame(i,m=metrics()){const c=m.crops[i],out=document.createElement('canvas');out.width=Math.max(1,Math.round(m.w));out.height=Math.max(1,Math.round(m.h));const ctx=out.getContext('2d');ctx.imageSmoothingEnabled=false;const fy=$('autoFeet').checked?footY(c):c.height-1;const baseline=Math.min(out.height-m.padY-1,m.padY+m.maxAbove-1+(+$('footOffset').value));const x=Math.round((out.width-c.width)/2),y=Math.round(baseline-fy);ctx.drawImage(c,x,y);return out}
function renderFrames(){els.list.innerHTML='';frames.forEach((f,i)=>{const card=document.createElement('div');card.className='frame-card'+(i===selected?' selected':'');card.draggable=true;const c=document.createElement('canvas');c.width=110;c.height=88;const cx=c.getContext('2d');cx.imageSmoothingEnabled=false;const crop=frameCrop(f);const sc=Math.min(c.width/crop.width,c.height/crop.height,3);cx.drawImage(crop,(c.width-crop.width*sc)/2,(c.height-crop.height*sc)/2,crop.width*sc,crop.height*sc);const meta=document.createElement('div');meta.className='frame-meta';meta.innerHTML=`<span>#${i+1}</span><span>${Math.round(f.w)}×${Math.round(f.h)}</span>`;card.append(c,meta);card.onclick=()=>{selected=i;renderFrames();renderSource();updateActionButtons();drawPreview(i)};card.addEventListener('dragstart',ev=>ev.dataTransfer.setData('text/plain',String(i)));card.addEventListener('dragover',ev=>ev.preventDefault());card.addEventListener('drop',ev=>{ev.preventDefault();const from=+ev.dataTransfer.getData('text/plain'),to=i;if(from===to)return;const [it]=frames.splice(from,1);frames.splice(to,0,it);selected=to;renderFrames();renderSource()});els.list.appendChild(card)});updateActionButtons()}

function drawPreview(i){pctx.clearRect(0,0,els.preview.width,els.preview.height);if(!img||!frames.length)return;const m=metrics(),n=normalizedFrame(Math.max(0,Math.min(i,frames.length-1)),m),scale=+$('previewScale').value;const w=n.width*scale,h=n.height*scale,x=(els.preview.width-w)/2,y=(els.preview.height-h)/2;pctx.imageSmoothingEnabled=false;pctx.drawImage(n,x,y,w,h);pctx.strokeStyle='rgba(255,255,255,.25)';const baseline=y+(Math.min(n.height-m.padY-1,m.padY+m.maxAbove-1+(+$('footOffset').value)))*scale+.5;pctx.beginPath();pctx.moveTo(0,baseline);pctx.lineTo(els.preview.width,baseline);pctx.stroke()}
function stopAnim(){if(animTimer){clearInterval(animTimer);animTimer=null}}
els.play.addEventListener('click',()=>{stopAnim();let a=Math.max(0,+$('startFrame').value-1),b=Math.min(frames.length-1,+$('endFrame').value-1);if(b<a)[a,b]=[b,a];let i=a;drawPreview(i);animTimer=setInterval(()=>{i=i>=b?a:i+1;drawPreview(i)},1000/Math.max(1,+$('fps').value))});els.stop.addEventListener('click',stopAnim);
['autoFeet','footOffset','padX','padY','cellW','cellH','previewScale'].forEach(id=>$(id).addEventListener('input',()=>drawPreview(selected>=0?selected:0)));

els.exportSheet.addEventListener('click',()=>{const m=metrics(),sc=+$('exportScale').value,cols=Math.max(1,+$('columns').value),rows=Math.ceil(frames.length/cols),out=document.createElement('canvas');out.width=Math.max(1,Math.round(m.w*cols*sc));out.height=Math.max(1,Math.round(m.h*rows*sc));const ctx=out.getContext('2d');ctx.imageSmoothingEnabled=false;frames.forEach((_,i)=>{const n=normalizedFrame(i,m),x=(i%cols)*m.w*sc,y=Math.floor(i/cols)*m.h*sc;ctx.drawImage(n,x,y,m.w*sc,m.h*sc)});downloadCanvas(out,'sprite_sheet.png');setStatus(`出力: ${out.width}×${out.height}px / ${frames.length}フレーム / セル ${m.w}×${m.h}`)});
els.exportFrames.addEventListener('click',async()=>{const m=metrics(),sc=+$('exportScale').value;for(let i=0;i<frames.length;i++){const n=normalizedFrame(i,m),out=document.createElement('canvas');out.width=Math.round(n.width*sc);out.height=Math.round(n.height*sc);const ctx=out.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(n,0,0,out.width,out.height);downloadCanvas(out,`frame_${String(i+1).padStart(3,'0')}.png`);await new Promise(r=>setTimeout(r,80))}setStatus(`${frames.length} 個の個別PNGを出力しました。ブラウザによっては複数ダウンロードの許可が必要です。`)});
function downloadCanvas(c,name){c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}

window.addEventListener('resize',()=>drawPreview(selected>=0?selected:0));
